services:
  ln-personal-page:
    ports:
      - "3000:3000"
    container_name: ln-personal-page-api
    image: ln-personal-page-api-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://ln-personal-page:ln-personal-page@ln-personal-page-db:5433/personal-page-db?schema=public
      - JWT_SECRET=''
      - JWT_EXPIRES_IN=30000
    depends_on:
      - ln-personal-page-db
    networks:
      - ln-personal-page-network
    

  ln-personal-page-db:
    image: ln-personal-page-postgres-image:17.5
    container_name: ln-personal-page-postgres
    restart: always
    build:
      context: ./docker/database/postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=ln-personal-page
      - POSTGRES_PASSWORD=ln-personal-page
      - POSTGRES_DB=personal-page-db
    volumes:
      - ln_personal_page_volume:/var/lib/postgresql/data
    networks:
      - ln-personal-page-network


volumes:
  ln_personal_page_volume:
    driver: local

networks:
  ln-personal-page-network:
    driver: bridge 