services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/personal-page-db?schema=public
      - JWT_SECRET=''
      - JWT_EXPIRES_IN=30000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal-page-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 